name: Setup Windows 11 RDP with Tailscale VPN

on:
  push:
    branches: [main]

env:
  TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
  RDP_USERNAME: "rdpuser"
  RDP_PASSWORD: "ParolaPuternica123"

jobs:
  setup-windows-rdp:
    runs-on: windows-2022
    timeout-minutes: 720  # 12 ore max execuție

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Add RDP User
        run: |
          net user $env:RDP_USERNAME $env:RDP_PASSWORD /add
          net localgroup "Remote Desktop Users" $env:RDP_USERNAME /add

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/windows-amd64/TailscaleSetup.exe" -OutFile "$env:TEMP\TailscaleSetup.exe"
          Start-Process -FilePath "$env:TEMP\TailscaleSetup.exe" -ArgumentList "/quiet" -Wait

      - name: Connect Tailscale with auth key
        run: |
          tailscale up --auth-key=$env:TAILSCALE_AUTH_KEY --accept-routes --run-service

      - name: Allow RDP through Tailscale VPN only
        run: |
          New-NetFirewallRule -DisplayName "Allow RDP via Tailscale" -Direction Inbound -Protocol TCP -LocalPort 3389 -RemoteAddress 100.64.0.0/10 -Action Allow
          New-NetFirewallRule -DisplayName "Allow RDP UDP via Tailscale" -Direction Inbound -Protocol UDP -LocalPort 3389 -RemoteAddress 100.64.0.0/10 -Action Allow

      - name: Set power settings to prevent sleep for 12 hours
        run: |
          powercfg /change standby-timeout-ac 720
          powercfg /change monitor-timeout-ac 720
          powercfg /change disk-timeout-ac 720

      - name: Show connection info
        run: |
          $ip = tailscale ip -4
          Write-Host "Connect RDP to IP: $ip"
          Write-Host "Username: $env:RDP_USERNAME"
          Write-Host "Password: $env:RDP_PASSWORD"

      - name: Keep alive 12 hours
        run: Start-Sleep -Seconds 43200
